### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by HoangNgo88** [Phoenix616/ConnectorPlugin#5]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by Phoenix616** [comment]
Really only because that's what I used in my setup already (redis is also used as key->value storage so it's nice not having to run yet another server)

Any other pupsub that support MQTT like RabbitMQ is supported too though. If you want support for others that don't just open an issue and I'll look into it. :)
